development:
  adapter: postgis
  encoding: utf8
  database: shopdiscovery
  pool: 5
  username: postgres
  password:

test: &TEST
  adapter: postgis
  encoding: utf8
  database: shopdiscovery_test
  pool: 5
  username: postgres
  password:

production:
  adapter: postgis
  encoding: utf8
  database: shopdiscovery_production
  pool: 5
  username: postgres
  password:

cucumber:
  <<: *TEST