development:
  adapter: postgis
  encoding: utf8
  database: shopdiscovery_backend_test
  pool: 5
  username: postgres
  password:

test: &TEST
  adapter: postgis
  encoding: utf8
  database: shopdiscovery_test
  template: template_postgis_20
  pool: 5
  username: postgres
  password:

production:
  adapter: postgis
  encoding: utf8
  database: shopdiscovery_production
  username: postgres
  password:

cucumber:
  <<: *TEST